Repository demokratie-live/democracy-client, pull requests merged in 2018-04, with the labels that each got.

#212 Sprint#8/airplane mode
  CHANGELOG.md
  index.js
  ios/democracyclient/Info.plist
  ios/fastlane/Fastfile
  package.json
  src/components/ActivityIndex.js
  src/graphql/client.js
  src/graphql/mutations/updateNetworkStatus.js
  src/graphql/queries/getNetworkStatus.js
  src/graphql/resolvers/index.js
  src/screens/Detail/Segments/VoteResults.js
  src/screens/Detail/Voting.js
  src/screens/Detail/index.js
  src/screens/Notifications/index.js
  src/screens/VoteList/List.js
  src/screens/VoteList/index.js
  src/screens/VoteVarification/BallotBox.js
  src/screens/Wrapper/NetworkStatus.js
  src/screens/index.js
  src/services/pushNotifications.js
  yarn.lock
Labels: bug

#213 fixed reloading bug of detailscreen android
  CHANGELOG.md
  ios/democracyclient/Info.plist
  package.json
  src/screens/Detail/index.js
Labels: DetailScreen, bug

#218 fixed support contacts
  CHANGELOG.md
  ios/democracyclient/Info.plist
  package.json
  src/screens/Support.js
Labels: bug

#244 Sprint#10/deployment client via tag
  .env.production.enc
  .gitignore
  .travis.yml
  Google_Play_Android_Developer.json.enc
  android/Google_Play_Android_Developer.json.enc
  android/app/build.gradle
  android/app/democracy2-release-key.keystore.enc
  democracy2-release-key.keystore.enc
  ios/fastlane/Appfile
  ios/fastlane/Fastfile
  secrets.tar.enc
Labels: enhancement

#228 corrected open icon to align with text
  CHANGELOG.md
  ios/democracyclient/Info.plist
  package.json
  src/components/ArgumentEntry/Message.js
Labels: enhancement

#222 Fixed Vote verification border color
  CHANGELOG.md
  ios/democracyclient/Info.plist
  package.json
  src/screens/VoteVarification/index.js
Labels: enhancement

#255 Sprint#10/deploy beta
  .env.production.alpha.enc
  .env.production.beta.enc
  .travis.yml
  android/fastlane/Fastfile
  ios/fastlane/Fastfile
Labels: enhancement

#287 build alpha only on fastlane test
  android/fastlane/Fastfile
Labels: enhancement

#286 dev version for android
  android/app/build.gradle
  android/app/src/dev/res/mipmap-hdpi/ic_launcher.png
  android/app/src/dev/res/mipmap-ldpi/ic_launcher.png
  android/app/src/dev/res/mipmap-mdpi/ic_launcher.png
  android/app/src/dev/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/dev/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/dev/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/dev/res/values/strings.xml
  package.json
Labels: enhancement

#290 New Sprint4 Video as Gif + YT Link
  README.md
Labels: enhancement

#221 Prevent Double Navigation
  CHANGELOG.md
  ios/democracyclient/Info.plist
  package.json
  src/hocs/NetworkStatus.js
  src/hocs/preventNavStackDuplicate.js
  src/screens/Search/index.js
  src/screens/VoteList/List.js
  src/screens/index.js
  yarn.lock
Labels: bug

#291 Metadata for each Flavor
  android/fastlane/Fastfile
  android/fastlane/metadata_alpha/android/de-DE/changelogs/1.txt
  android/fastlane/metadata_alpha/android/de-DE/full_description.txt
  android/fastlane/metadata_alpha/android/de-DE/images/icon.png
  android/fastlane/metadata_alpha/android/de-DE/short_description.txt
  android/fastlane/metadata_alpha/android/de-DE/title.txt
  android/fastlane/metadata_alpha/android/de-DE/video.txt
  android/fastlane/metadata_beta/android/de-DE/changelogs/1.txt
  android/fastlane/metadata_beta/android/de-DE/full_description.txt
  android/fastlane/metadata_beta/android/de-DE/images/icon.png
  android/fastlane/metadata_beta/android/de-DE/short_description.txt
  android/fastlane/metadata_beta/android/de-DE/title.txt
  android/fastlane/metadata_beta/android/de-DE/video.txt
Labels: bug, enhancement

#297 [Hotfix] metadata paths
  android/fastlane/Fastfile
Labels: Android, bug

#305 Sprint#11/disable push notifications
  CHANGELOG.md
  index.js
  ios/democracyclient/Info.plist
  package.json
  src/components/VoteButton.js
  src/screens/Detail/Voting.js
  src/screens/Detail/index.js
  src/screens/Notifications/InAppNotification.js
  src/screens/VoteVarification/BallotBox.js
  src/screens/index.js
Labels: bug
