Repository demokratie-live/democracy-client, pull requests merged in 2018-02, with the labels that each got.

#79 fixed tutorial screen
  src/screens/Instructions.js
  src/screens/Instructions/Slide.js
  src/screens/Instructions/index.js
  src/screens/SideMenu/Navigation.js
Labels: enhancement

#99 Sprint#5/versioning
  android/app/build.gradle
  android/build.gradle
  ios/democracyclient/Info.plist
  package.json
  version-ios.sh
Labels: enhancement

#94 Sprint#5/refetch
  src/graphql/client.js
  src/screens/Detail/index.js
  src/screens/VoteList/List.js
Labels: bug

#102 increase header padding on ios list header
  src/screens/VoteList/Header.js
  src/screens/VoteList/List.js
Labels: Layout

#105 Details Seite springt
  src/screens/Detail/index.js
Labels: bug

#119 schare democracyclient-prod scheme for travis
  ios/democracyclient.xcodeproj/xcshareddata/xcschemes/democracyclient-prod.xcscheme
Labels: bug

#120 add -quiet mode
  package.json
Labels: bug

#115 Add security Screen
  assets/images/sescurity-process.png
  assets/images/sescurity-process@2x.png
  assets/images/sescurity-process@3x.png
  src/screens/Security.js
  src/screens/SideMenu/Navigation.js
  src/screens/Support.js
  src/screens/index.js
Labels: Layout

#116 add margin-bottom to menu segment-headers
  src/screens/SideMenu/Navigation.js
Labels: Layout

#117 add Baby to sideMenu for instructions
  assets/icons/baby.png
  assets/icons/baby@2x.png
  assets/icons/baby@3x.png
  src/screens/SideMenu/Navigation.js
Labels: Layout

#118 Update PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: improvement
