Repository demokratie-live/democracy-client, pull requests merged in 2018-03, with the labels that each got.

#123 improve splash screens
  ios/democracyclient.xcodeproj/project.pbxproj
  ios/democracyclient/Images.xcassets/Contents.json
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/Contents.json
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/Default-568h@2x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/Default-667h@2x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/Default-Landscape-736h@3x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/Default-Landscape-812h@3x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/Default-Landscape.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/Default-Landscape@2x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/Default-Portrait-736h@3x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/Default-Portrait-812h@3x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/Default-Portrait.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/Default-Portrait@2x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/Default@2x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPad Landscape Without Status Bar iOS 5,6 1x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPad Landscape Without Status Bar iOS 5,6 2x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPad Portrait 7-9 1x-1.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPad Portrait 7-9 1x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPad Portrait 7-9 2x-1.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPad Portrait 7-9 2x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPad Portrait Without Status Bar iOS 5,6 1x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPad Portrait Without Status Bar iOS 5,6 2x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPad-1.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPad.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPad@2x-1.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPad@2x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPhone 8 Plus@3x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPhone 8@2x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPhone Landscape iOS 8.9 Retina HD 5.5 2208x1242px.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPhone Portrait 5,6.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPhone Portrait 7-10.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPhone Portrait 7-9 Retina 4.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPhone Portrait 7-9.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPhone SE@2x.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPhone X Landscape iOS 11+ 2436x1125px.png
  ios/democracyclient/Images.xcassets/LaunchImage.launchimage/iPhone X@3x.png
  ios/democracyclient/Info.plist
Labels: Layout

#131 side menu background
  assets/images/bitmap.jpg
  assets/images/bitmap.png
  assets/images/bitmap@2x.jpg
  assets/images/bitmap@2x.png
  assets/images/bitmap@3x.jpg
  assets/images/bitmap@3x.png
  assets/images/stars2.png
  src/screens/SideMenu/index.js
Labels: Layout

#144 [Android] reset search results on click X
  src/screens/Search/Header.android.js
Labels: bug

#145 fix search status issue
  src/screens/Search/Header.android.js
  src/screens/Search/Header.ios.js
  src/screens/Search/index.js
Labels: improvement

#151 Sprint#6/encrypted webhook
  .travis.yml
Labels: bug

#177 Sprint#7/fix permissions
  .travis.yml
  CHANGELOG.md
  android/app/src/main/AndroidManifest.xml
  ios/democracyclient/Info.plist
  package.json
Labels: bug

#187 remove emoji from changelog
  CHANGELOG.md
  ios/democracyclient/Info.plist
  package.json
Labels: bug
