Repository demokratie-live/democracy-client, pull requests merged in 2019-10, with the labels that each got.

#886 Alpha/master
  CHANGELOG.md
  ios/democracyclient/Info.plist
  package.json
  src/screens/About/content.js
  src/screens/Detail/Segments/VoteResults/GovernmentVoteResults/Deputy.js
  src/screens/Profil/MemberProfil/index.js
  src/screens/WahlOMeter/Wahlkreis/index.js
Labels: #Bug

#906 🛠 [Documentation] Changed ReadMe to reflect the Maintainers Images as per Github
  README.md
Labels: #Enhancement

#812 Removed unnecessary comments and fixed #808
  src/screens/Imprint/content.js
Labels: #Bug, #Enhancement
